/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.akademik;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author adtya
 */
public class entrymatakuliah extends javax.swing.JFrame {

    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    /**
     * Creates new form entrymatakuliah
     */
    public entrymatakuliah() {
        initComponents();
        koneksi();
    }
    
    private void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbakademik", "root", "");
            stat = con.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void bersih(){
        vkdmtk.setText("");
        vnamamtk.setText("");
        vsks.setText("");
        //arakan form ponter mouse pada textfield yang ingin 
        vkdmtk.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vkdmtk = new javax.swing.JTextField();
        vnamamtk = new javax.swing.JTextField();
        vsks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ENTRY DATA MATAKULIAH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 160, 16);

        jLabel2.setText("KODE MATAKULIAH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 110, 16);

        jLabel3.setText("NAMA MATAKULIAH");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 120, 16);

        jLabel4.setText("SKS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 40, 16);

        vkdmtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vkdmtkActionPerformed(evt);
            }
        });
        getContentPane().add(vkdmtk);
        vkdmtk.setBounds(170, 70, 100, 22);
        getContentPane().add(vnamamtk);
        vnamamtk.setBounds(170, 100, 180, 22);
        getContentPane().add(vsks);
        vsks.setBounds(170, 130, 50, 22);

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 210, 77, 25);

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 210, 59, 25);

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 210, 71, 25);

        jButton4.setText("BATAL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 210, 69, 25);

        jButton5.setText("KELUAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 210, 79, 25);

        setBounds(0, 0, 468, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            stat.executeUpdate("insert into matakuliah values ("
                                    + "'"+vkdmtk.getText()+"',"
                                    + "'"+vnamamtk.getText()+"',"
                                    + "'"+vsks.getText()
                                    +"')"
            );
            
            bersih();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan....");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan Error : " +e );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
           stat.executeUpdate("update matakuliah set "
                             + "namamtk='"+vnamamtk.getText()+"',"
                             + "sks='"+vsks.getText()+"'"
                             + " where "
                             + "kdmtk='"+vkdmtk.getText()+"'"
                            );
           bersih();
           JOptionPane.showMessageDialog(null, "Data Berhasil Diedit....");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan Error : " +e );
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vkdmtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vkdmtkActionPerformed
        try{
            
            res=stat.executeQuery("select * from matakuliah where " 
                                 + "kdmtk='"+vkdmtk.getText()+"'"
                                );
            while (res.next()) {
                vnamamtk.setText(res.getString("namamtk"));
                vsks.setText(res.getString("sks")); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan Error : " +e );
        }
    }//GEN-LAST:event_vkdmtkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            stat.executeUpdate("delete from matakuliah where "
                             + "kdmtk='"+vkdmtk.getText()+"'"
            );
            
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus....");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan Error : " +e );
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       bersih();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrymatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrymatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrymatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrymatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrymatakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField vkdmtk;
    private javax.swing.JTextField vnamamtk;
    private javax.swing.JTextField vsks;
    // End of variables declaration//GEN-END:variables
}
