/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.akademik;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author adtya
 */
public class entrynilai extends javax.swing.JFrame {

    private Connection con;
    private Statement stat;
    private ResultSet res;
    private String tgl1;
    /**
     * Creates new form entrynilai
     */
    public entrynilai() {
        initComponents();
        koneksi();
        isicomboNOBP();
        isicomboKDMTK();
    }

    private void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbakademik", "root", "");
            stat = con.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }    
    
    private void bersih(){
        vnobp.setSelectedIndex(-1);
        vkdmtk.setSelectedIndex(-1);
        vnama.setText("");
        vnamamtk.setText("");
        
        vnilaitugas.setText("");
        vnilaimid.setText("");
        vnilaisemester.setText("");
        vnilaiakhir.setText("");
        vnilaihuruf.setText("");
        
        vnobp.requestFocus();
    }
    
    private void isicomboNOBP(){
    try {
        vnobp.addItem("");
        res=stat.executeQuery("select * from mahasiswa");
        
        while (res.next()) {            
            vnobp.addItem(res.getString("nobp"));
        }
        vnobp.setSelectedIndex(-1);
    } catch (Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }
    
    private void isicomboKDMTK(){
    try{
            vkdmtk.addItem("");
            res=stat.executeQuery("select * from matakuliah ");
            
            while (res.next()) {            
                vkdmtk.addItem(res.getString("kdmtk"));
        }
            vkdmtk.setSelectedIndex(-1);
    
    } catch (Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vnobp = new javax.swing.JComboBox();
        vkdmtk = new javax.swing.JComboBox();
        vnilaitugas = new javax.swing.JTextField();
        vnilaimid = new javax.swing.JTextField();
        vnilaisemester = new javax.swing.JTextField();
        vnilaiakhir = new javax.swing.JTextField();
        vnilaihuruf = new javax.swing.JTextField();
        vnama = new javax.swing.JTextField();
        vnamamtk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ENTRY DATA NILAI");

        jLabel2.setText("NO BP");

        jLabel3.setText("KODE MATAKULIAH");

        jLabel4.setText("NILAI TUGAS");

        jLabel5.setText("NILAI MID");

        jLabel6.setText("NILAI SEMESTER");

        jLabel7.setText("NILAI AKHIR");

        jLabel8.setText("NILAI HURUF");

        vnobp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnobpActionPerformed(evt);
            }
        });

        vkdmtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vkdmtkActionPerformed(evt);
            }
        });

        vnilaihuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnilaihurufActionPerformed(evt);
            }
        });

        vnamamtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnamamtkActionPerformed(evt);
            }
        });

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("HAPUS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("BATAL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("KELUAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vkdmtk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vnobp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vnilaihuruf, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(vnilaiakhir)
                                            .addComponent(vnilaisemester)
                                            .addComponent(vnilaimid)
                                            .addComponent(vnilaitugas))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vnama)
                            .addComponent(vnamamtk, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vnobp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vkdmtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vnamamtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vnilaitugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vnilaimid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vnilaisemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vnilaiakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vnilaihuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vnamamtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnamamtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnamamtkActionPerformed

    private void vnilaihurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnilaihurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnilaihurufActionPerformed

    private void vnobpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnobpActionPerformed
       try {
            res=stat.executeQuery("select * from mahasiswa where "
                                + "nobp='"+vnobp.getSelectedItem()+"'"
            );
            
            while (res.next()) {               
               vnama.setText(res.getString("nama"));
           }
       } catch (Exception e ){
           JOptionPane.showMessageDialog(rootPane, e);
       }
    }//GEN-LAST:event_vnobpActionPerformed

    private void vkdmtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vkdmtkActionPerformed
        //menampilkan nama dari kode matakuliah yang dipilih
        try {
            res=stat.executeQuery("select * from matakuliah where "
                                    + "kdmtk='"+vkdmtk.getSelectedItem()+"'"
            );
            while (res.next()) {                
                vnamamtk.setText(res.getString("namamtk"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
        //menampilkan data nilai berdarsarkan nobp dan kode matakuliah
        try {
            res=stat.executeQuery("select * from nilai where "
                                 +"nobp='"+vnobp.getSelectedItem()+"'"
                                 +"and "
                                 +"kdmtk='"+vkdmtk.getSelectedItem()+"'"
                                 );
            while (res.next()) {                
                vnilaitugas.setText(res.getString("nilaitugas"));
                vnilaimid.setText(res.getString("nilaimid"));
                vnilaisemester.setText(res.getString("nilaisemester"));
                vnilaiakhir.setText(res.getString("nilaiakhir"));
                vnilaihuruf.setText(res.getString("nilaihuruf"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_vkdmtkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double totaltugas,totalmid,totalsemester, total;
       
       totaltugas=(Double.parseDouble(vnilaitugas.getText())* 20 ) /100;
       totalmid=(Double.parseDouble(vnilaimid.getText())* 30 ) / 100;
       totalsemester=(Double.parseDouble(vnilaisemester.getText()) * 50) /100;
       
       total=totaltugas+totalmid+totalsemester;
       vnilaiakhir.setText(String.valueOf(total));
       
        if (total >= 80) {
            vnilaihuruf.setText("A");
        } else if (total < 80 && total >= 65){
            vnilaihuruf.setText("B");
        } else if(total < 65 && total >= 55 ){
            vnilaiakhir.setText("C");
        } else if(total < 55 && total >= 40){
            vnilaihuruf.setText("D");
        } else{
            vnilaihuruf.setText("E");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            stat.executeUpdate("insert into nilai values ("
                    +"'"+vnobp.getSelectedItem()+"',"
                    +"'"+vkdmtk.getSelectedItem()+"',"
                    +"'"+vnilaitugas.getText()+"',"
                    +"'"+vnilaimid.getText()+"',"
                    +"'"+vnilaisemester.getText()+"',"
                    +"'"+vnilaiakhir.getText()+"',"
                    +"'"+vnilaihuruf.getText()
                    +"')"
            );
            bersih();
            JOptionPane.showMessageDialog(null, "Data berhasil Disimpan..");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Keterangan error :" +e) ;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            stat.executeUpdate("update nilai set "
                    +"nilaitugas='"+vnilaitugas.getText()+"',"
                    +"nilaimid='"+vnilaimid.getText()+"',"
                    +"nilaisemester='"+vnilaisemester.getText()+"',"
                    +"nilaiakhir='"+vnilaiakhir.getText()+"',"
                    +"nilaihuruf='"+vnilaihuruf.getText()+"'"
                    +"where "
                    +"nobp='"+vnobp.getSelectedItem()+"'"
                    +"and "
                    +"kdmtk='"+vkdmtk.getSelectedItem()+"'"
                    );
            bersih();
            JOptionPane.showMessageDialog(rootPane, "Data Berhasik Diedit..");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            stat.executeUpdate("delete from nilai where "
                    + "nobp='"+vnobp.getSelectedItem()+"'"
                    + "and "
                    + "kdmtk='"+vkdmtk.getSelectedItem()+"'"
                    );
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiHapus....");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pesan salah: "+e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        bersih();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrynilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrynilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox vkdmtk;
    private javax.swing.JTextField vnama;
    private javax.swing.JTextField vnamamtk;
    private javax.swing.JTextField vnilaiakhir;
    private javax.swing.JTextField vnilaihuruf;
    private javax.swing.JTextField vnilaimid;
    private javax.swing.JTextField vnilaisemester;
    private javax.swing.JTextField vnilaitugas;
    private javax.swing.JComboBox vnobp;
    // End of variables declaration//GEN-END:variables
}
